### ISSUE TITLE
咨询: 是否有对应文章/视频资料

### ISSUE THREAD

**Issue by asurance** [silent-rain/stm32f103-tutorial#1]

**Comment by silent-rain** [comment]
可以参考[江协科技Up主](https://www.bilibili.com/video/BV1th411z7sn?p=1&vd_source=c459b4f4f90bc42bb5ddb5baf12e1bc7)的教学视频，我是基于这个视频进行学习并记录了一些使用示例

**Comment by asurance** [comment]
我看视频中好像不是用的rust...

**Comment by silent-rain** [comment]
原视频是c语言的，我基于视频对应摸索了一些rust示例，暂时没有rust的视频~
